github4ta/taf-onliner5

src/main/java/Main.java
=> Want to merge Tatjana B. branch

src/main/java/HomePage.java
=> UI-002 - Create Page object

pom.xml
Добавление в pom.xml Webdriver
=> UI-021 - pom.xml - add WebDriver

src/main/java/LoginFormPage.java
=> UI-004 - Login form page - Enter label locator

pom.xml
=> UI-022 - pom.xml - add Faker

src/test/java/HomeTest.java
=> UI-030 - Create HomeTest class

src/main/java/HomePage.java
=> UI-011 - Main menu - News item

src/main/java/LoginFormPage.java
=> UI-007 - Login form page - Button Login locator

src/main/java/HomePage.java, src/main/java/LoginFormPage.java
=> UI-014 - Main menu - Services item

src/main/java/HomePage.java
добавила в класс поле WebDriver driver;
добавила в класс конструктор с параметром HomePage(WebDriver driver);
=> UI-050 - Home page - add WebDriver field and Constructor with WebDriver parameter

src/main/java/LoginFormPage.java
add inputNickNameLocator to LoginFormPage class
=> UI-005 - Login form page - Email input locator

src/main/java/LoginFormPage.java
Used xpath intentionally as it is more reliable and concise than class name.
=> UI-006 - Login form page - Password input locator

src/main/java/LoginFormPage.java
=> UI-008 - Login form page - Error message Email locator

src/main/java/LoginFormPage.java
Reverts github4ta/taf-onliner5#29
=> Revert "UI-008 - Login form page - Error message Email locator"

src/main/java/HomePage.java
=> UI-016 - Main menu - Forum item

pom.xml
=> UI-020 - pom.xml - add JUnit5

src/main/java/HomePage.java
=> UI-100 - Home page - Main menu - click button Enter

src/main/java/HomePage.java
=> UI-102 - Home page - Main menu - click menu item News

src/main/java/HomePage.java, src/main/java/Main.java
add line with buttonCatalogItemXpath
=> UI-010 - Main menu - Catalog item

src/main/java/HomePage.java
add FleaItem (Барахолка) locator
=> UI-015 - Main menu - Flea item

src/main/java/HomePage.java
добавила в HomePage метод клика на разделе основного меню "Услуги".
=> UI-101 - Home page - Main menu - click menu item Services

src/main/java/HomePage.java
want to add locator buttonHousesAndApartmentsXPath
=> UI-013 - Main menu - Houses item

src/main/java/HomePage.java, src/test/java/Test.java
want add methods before and after to test class
=> UI 500   test class   before and after methods

src/main/java/HomePage.java
add method clickItemFlea (Барахолка)
=> UI-106 - Home page - Main menu - click menu item Flea

src/main/java/LoginFormPage.java
add errorMessagePasswordXpath and refactor errorMessageEmailXpath
=> UI-009 - Login form page - Error message Password locator

src/test/java/HomeTest.java
add inheritance from Test class
=> UI-501 - HomeTest class - inheritance from Test class

src/test/java/LoginFormTest.java
create LoginFormTest with inheritance from Test class
=> UI-600 - LoginFormTest class - inheritance from Test class

src/main/java/HomePage.java
=> UI-110 - Home page - get footer text

src/main/java/LoginFormPage.java, src/test/java/LoginFormTest.java
add method compareEmailPlaceholder
=> UI-602 - LoginFormTest - сheck Login form placeholder e-mail

src/main/java/HomePage.java, src/test/java/HomeTest.java
add line with buttonHousesAndApartmentsItemXpath
=> UI-108 - Home page - Main menu - click menu item Houses

src/main/java/HomePage.java
=> UI-104 - Home page - Main menu - click menu item Forum

src/main/java/HomePage.java
=> UI-107 - Home page - Main menu - click menu item Catalog

src/test/java/PageTest.java
want added driver initialization and driver.quit in PageTest
=> UI - 503 - PageTest - refactor

src/main/java/HomePage.java
add the field url and method opening the site, refactor clickButtonForum method, aligned with @nikitashikin1
=> UI-117-Home page - open homepage method

src/main/java/HomePage.java
task:
добавить в HomePage baseUrl "https://www.onliner.by/"
=> UI-017 -Main menu - add baseUrl
